import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

const repoRoot = path.resolve(import.meta.dirname, "..", "..");
const templatePath = "tasks/templates/data-package-to-tidas-activity-data.md";
interface FileLocationEntry {
  id: string;
  current_path: string;
  referenced_by?: string[];
  tracked?: boolean;
}

interface FileLocationRegistry {
  updated_at_utc: string;
  entries: FileLocationEntry[];
}

function readText(relativePath: string): string {
  return fs.readFileSync(path.join(repoRoot, relativePath), "utf8");
}

function readJson<T>(relativePath: string): T {
  return JSON.parse(readText(relativePath)) as T;
}

test("enterprise activity-data workflow accepts one uploaded XLSX", () => {
  const template = readText(templatePath);

  assert.match(template, /^kind: source-evidence-dataset-development$/mu);
  assert.match(template, /^dataset_type: process$/mu);
  assert.match(template, /^profile: generic$/mu);
  assert.match(template, /^allow_remote_commit: false$/mu);
  assert.match(template, /^source_file: "\/abs\/path\/<uploaded-workbook>\.xlsx"$/mu);
  assert.match(
    template,
    /The only user-supplied input for this workflow is one `\.xlsx` workbook\./u,
  );
  assert.match(template, /does not assume a functional unit, system boundary, geography/u);
  assert.match(
    template,
    /configured structured-spreadsheet capability owns read-only workbook inspection/u,
  );
  assert.match(template, /`seed-manifest\.json` is mandatory for this source-evidence lane/u);
  assert.match(template, /extraction\/workbook-structure\.json/u);
  assert.match(template, /extraction\/workbook-extraction-receipt\.json/u);
  assert.match(template, /extraction\/records\.jsonl/u);
  assert.match(template, /evidence\/sources\.jsonl/u);
  assert.match(template, /evidence\/chunks\.jsonl/u);
  assert.match(template, /evidence\/field-evidence\.jsonl/u);
  assert.match(template, /evidence\/conflicts\.jsonl/u);
  assert.doesNotMatch(template, /^source_document:/mu);
  assert.doesNotMatch(template, /^prototype_seed:/mu);

  for (const required of [
    "pnpm exec tiangong-lca dataset author",
    "--input /abs/path/uploaded-workbook.xlsx",
    "pnpm exec tiangong-lca dataset context-pack",
    "pnpm exec tiangong-lca flow build-plan validate",
    "pnpm exec tiangong-lca flow build-plan materialize",
    "pnpm exec tiangong-lca process build-plan validate",
    "pnpm exec tiangong-lca process build-plan materialize",
    "node scripts/foundry.ts dataset-tidas-validate",
    "node scripts/foundry.ts dataset-curation-gate",
    "node scripts/foundry.ts dataset-authoring-plan",
    "node scripts/foundry.ts dataset-post-authoring-finalize",
    "pnpm account:run",
  ]) {
    assert.match(template, new RegExp(required.replaceAll(/[.*+?^${}()|[\]\\]/gu, "\\$&"), "u"));
  }

  const floatingRunner = ["n", "px"].join("");
  const floatingTag = ["@", "latest"].join("");
  assert.equal(template.includes(floatingRunner), false);
  assert.equal(template.includes(floatingTag), false);
  assert.doesNotMatch(template, /converter\/(?:bom-to-tidas\.py|run\.sh)/u);
  assert.doesNotMatch(template, /--skip-validate\b/u);
  assert.doesNotMatch(template, /--commit\b/u);
  assert.doesNotMatch(template, /source\s+[^\n]*\.env/u);
  assert.match(template, /No command in this template performs a remote write\./u);
});

test("template accepts structured spreadsheet evidence and fails closed on semantic gaps", () => {
  const template = readText(templatePath);

  assert.match(template, /`candidate`[\s\S]*affected row\/scope stays blocked pending a decision/u);
  assert.match(
    template,
    /`manual_review`[\s\S]*affected row\/scope stays blocked pending a decision/u,
  );
  assert.match(template, /do not insert the annual total into the target functional-unit process/u);
  assert.match(template, /dictionary miss never copies source-language text into an `en` field/u);
  assert.match(template, /evidence-backed English exists for every required multilingual field/u);
  assert.match(template, /specs\/canonical-support\/flow-properties-unit-groups\.json/u);
  assert.match(template, /Canonical UUID replacement never silently converts amounts\./u);
  assert.match(
    template,
    /Do not create ordinary writable source rows for data-format or compliance placeholders\./u,
  );
  assert.match(
    template,
    /Evidence generated by a configured structured-spreadsheet capability is admissible/u,
  );
  assert.match(template, /workbook sheet names, order and visibility, used ranges/u);
  assert.match(template, /merged ranges with their anchor cells/u);
  assert.match(
    template,
    /raw typed values, data types, displayed values[\s\S]*formulas[\s\S]*headers[\s\S]*source units/u,
  );
  assert.match(template, /extractor name and version/u);
  assert.match(template, /same workbook bytes, extraction contract, extractor version/u);
  assert.match(
    template,
    /do not fail merely because the authoring extract itself is page- or text-oriented/u,
  );
  assert.match(
    template,
    /Document fulltext, screenshots, or page chunks[\s\S]*do not replace cell\/formula\/merged-range lineage/u,
  );
  assert.match(template, /structured_spreadsheet_extraction_unavailable/u);
  assert.match(
    template,
    /only when every configured structured-spreadsheet route is unavailable or fails/u,
  );
  assert.match(
    template,
    /do not implement a task-local parser or promote one-off inspection code into a canonical converter/u,
  );
  assert.match(
    template,
    /`status=evidence_ready` means that source text and contract packs exist; it does not by itself prove record-level workbook decomposition or candidate rows/u,
  );
});

test("template is dataset-agnostic and registered as a generic workflow", () => {
  const template = readText(templatePath);
  const registry = readJson<FileLocationRegistry>("docs/file-location-registry.json");
  const entries = new Map(registry.entries.map((entry) => [entry.id, entry]));
  const templateEntry = entries.get("data-package-to-tidas-activity-data-template");

  assert.match(registry.updated_at_utc, /^2026-08-26T/u);
  assert.equal(templateEntry?.current_path, templatePath);
  assert.equal(templateEntry?.tracked, true);
  assert.deepEqual(templateEntry?.referenced_by, [
    "tasks/README.md",
    "test/unit/data-package-template-contract.test.mts",
  ]);
  for (const sampleSpecificTerm of [
    "fpcb",
    "flexible printed circuit",
    "柔性",
    "fpc-sim",
    "产品级bom",
    "合成活动主表",
  ]) {
    assert.equal(
      template.toLocaleLowerCase().includes(sampleSpecificTerm),
      false,
      sampleSpecificTerm,
    );
  }
  assert.doesNotMatch(template, /default system boundary is cradle-to-gate/iu);
  assert.doesNotMatch(template, /per-1,000-item/iu);
  assert.doesNotMatch(template, /one-item or one-batch/iu);

  const gitignore = readText(".gitignore");
  assert.match(gitignore, /!tasks\/templates\/\*\.md/u);
  assert.doesNotMatch(gitignore, /inputs\/source-documents/u);

  const taskGuide = readText("tasks/README.md");
  assert.match(taskGuide, /uploads one enterprise `\.xlsx` workbook/u);
  assert.match(taskGuide, /workbook is the only user-supplied input/u);

  for (const contractPath of ["WORKFLOW.md", ".agents/skills/foundry-tidas-import/SKILL.md"]) {
    const contract = readText(contractPath);
    assert.match(contract, /Write-ready rows preserve every source-language variant/u);
    assert.match(
      contract,
      /evidence-backed `en` values for every TIDAS-required multilingual field/u,
    );
    assert.doesNotMatch(contract, /Rows remain source-language before import/u);
    assert.doesNotMatch(contract, /Import-ready rows are source-language rows/u);
  }
});
